version: "3.7"

networks:
  docker.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: unless-stopped
    container_name: docker.php
    tty: true
    depends_on:
      - db
    networks:
      - docker.network
    volumes:
      - ./src:/var/www

  nginx:
    build: ./docker/nginx
    container_name: docker.nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - php
    ports:
      - "80:80"
    networks:
      - docker.network
    volumes:
      - ./src:/var/www

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/postgres/db_data:/var/lib/postgresql/data
    networks:
      - docker.network

  smtp:
    platform: linux/x86_64
    image: mailhog/mailhog
    container_name: docker-workspace-smtp
    logging:
      driver: 'none'
    ports:
      - "8003:1025"
      - "8100:8025"
    networks:
      - docker.network